[project]
name = "tgfm"
version = "0.1.0"
description = "Text-Graph Foundation Model."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.6",
    "pre-commit>=4.5.1",
    "torch>=2.4.1",
    "torch-geometric>=2.7.0",
    "tqdm>=4.67.3",
    "transformers>=5.4.0",
]

[dependency-groups]
dev = [
    "cmake>=3.27,<4.0",
    "matplotlib>=3.10.8",
    "mypy>=1.19.1",
    "nemo-curator[text-cuda12]>=1.1.0",
    "ogb>=1.3.6",
    "polars>=1.40.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
    "seaborn>=0.13.2",
]

[tool.flit.module]
name = "tgfm"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"





[tool.mypy]
files = ['tgfm']
exclude = ['^test/']
install_types = true
non_interactive = true
ignore_missing_imports = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
skip = [".gitignore", "__init__.py"]

[tool.ruff]
exclude = ['test']

[tool.ruff.lint]
select = [
    "D",  # pydocstyle
]
ignore = [
    "D100",  # Ignore "Missing docstring in public module"
    "D101",  # Ignore "Missing docstring in public class"
    "D102",  # Ignore "Missing docstring in public method"
    "D103",  # Ignore "Missing docstring in public function"
    "D104",  # Ignore "Missing docstring in public package"
    "D105",  # Ignore "Missing docstring in magic method"
    "D107",  # Ignore "Missing docstring in __init__"
    "D205",  # Ignore "blank line required between summary line and description"
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
addopts = [
    "--capture=no",
    "--color=yes",
    "-vvv",
]
markers = [
    "integration: marks integration tests (deselect with '-m \"not integration\"')"
]

[tool.coverage.run]
source = ["tgfm"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "pass",
    "raise NotImplementedError",
    "register_parameter",
    "torch.cuda.is_available",
]
