MetaArguments:
  log_file_path: "unigraph_ogb_pretraining.log"
  node_file: ""
  edge_file: ""
  save_dir: "ogb_100m/weights/"
  root_dir: "ogb_100m/"
  is_scratch_location: true
  global_seed: 42

ExperimentArguments:
  exp_args:
    Unigraph:
      model_args:
        model: "Unigraph"
        num_layers: 3
        num_neighbors: [10, 10]
        batch_size: 1024
        dropout: 0.2
        lr: 2.0e-5
        weight_decay: 0.001
        epochs: 100
        device: 0
      data_args:
        task_name: "pre-training"
