MetaArguments:
  log_file_path: "simpleGCN_legraph.log"
  node_file: ""
  edge_file: ""
  root_dir: ""
  is_scratch_location: true
  global_seed: 42

ExperimentArguments:
  exp_args:
    LeGraph:
      model_args:
        model: "SimpleMPNN"
        epochs: 80
        batch_size: 16
        dropout: 0.2
        lr: 1.0e-3
        weight_decay: 1.0e-5
        device: 0
        eval_frequency: 0
        eval_repeat: 10
        log_frequency: 10
        num_local_parts: 8
        num_local_as_global: 2
      data_args:
        data_name: 'cora'
        task_name: ""
